/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiBavRouteImport } from './routes/api/bav'
import { Route as ApiKycRouteImport } from './routes/api/kyc'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBavRoute = ApiBavRouteImport.update({
  id: '/api/bav',
  path: '/api/bav',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKycRoute = ApiKycRouteImport.update({
  id: '/api/kyc',
  path: '/api/kyc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/bav': typeof ApiBavRoute
  '/api/kyc': typeof ApiKycRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/bav': typeof ApiBavRoute
  '/api/kyc': typeof ApiKycRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/bav': typeof ApiBavRoute
  '/api/kyc': typeof ApiKycRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/bav' | '/api/kyc'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/bav' | '/api/kyc'
  id: '__root__' | '/' | '/api/bav' | '/api/kyc'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBavRoute: typeof ApiBavRoute
  ApiKycRoute: typeof ApiKycRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bav': {
      id: '/api/bav'
      path: '/api/bav'
      fullPath: '/api/bav'
      preLoaderRoute: typeof ApiBavRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kyc': {
      id: '/api/kyc'
      path: '/api/kyc'
      fullPath: '/api/kyc'
      preLoaderRoute: typeof ApiKycRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBavRoute: ApiBavRoute,
  ApiKycRoute: ApiKycRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
